### ISSUE TITLE
Integrate Visual Analysis with MATLAB

### ISSUE THREAD

**Issue by kennedyengineering** [kennedyengineering/EE525_Final_Project#18]
- [x] Perform analysis with experimental data, see #17
- [ ] Compute state via gyro, see #20
- [ ] Compute state via accel, see #21 
- [ ] Calibrate IMU axis, new PR

**Comment by kennedyengineering** [comment]
When the IMU is stationary at the end of the data collection, where it is suspended via a USB cable, the IMU axis is not exactly aligned with the plane of movement. Need to rotate along Z gyro axis. 

Accel:
Measure tangential acceleration in Z, convert to angular acceleration (using constants in model), then integrate to get angular velocity.

Gyro:
Measure angular velocity directly.

Angular velocity can be integrated to get theta. Each sensor should be able to predict the state of the pendulum independently.

We haven't gotten to sensor fusion yet, right?

**Comment by kennedyengineering** [comment]
The C matrix is identity is that an issue?

Our 'states' of the pendulum are theta, d_theta, and they are determined by the 'states' the IMU measures -- acceleration and angular velocity. The observability matrix is computed via A and C matrices, which do not incorporate the IMU 'states'. Something about that seems weird -- wouldn't the observability of the pendulum's states by the IMU be a point of analysis?

**Comment by kennedyengineering** [comment]
McKell Notes: linearize inverse cosine? system model is decent as is. deal with non-linearities later. sensor fusion is part 4. the system has two states, sensors have various outputs. don't worry about gyroscope / accel independent state estimates.
