### ISSUE TITLE
Finalize Arduino Code

### ISSUE THREAD

**Issue by kennedyengineering** [kennedyengineering/EE525_Final_Project#3]
Necessary features/improvements:
- [x] Add timestamp to Arduino (See MR #2)
- [x] Maximize Arduino output rate (See MR #4)
- [ ] Add 'screen' based Linux/OSX serial logging utility script (See MR #5)
- [x] Add necessary Python post-processing/formatting scripts

**Comment by kennedyengineering** [comment]
Maximizing the Arduino output rate should be as simple as 1) decreasing the number of characters transmitted 2) maybe decreasing the number of print statements (if performance betters) 3) moving away from transmitting chars to transmitting structs (estimate performance improvement before attempting, challenging on the RX side of things but it has been done).

**Comment by kennedyengineering** [comment]
Don't use Python for post processing, using MATLAB

**Comment by kennedyengineering** [comment]
Just used Putty for logging...
